spring.profiles.active=${paramProfile:local}
server.port=${PORT:8000}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info

logging.level.root=INFO
logging.level.org.springframework.web=INFO
