spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema="CW-IMO-QAS"

spring.jackson.time-zone=IST
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

logging.level.org.springframework.web=INFO
spring.cloud.config.enabled=false

spring.user.roles={"Admin":"Z:CWQ_IMO_PM_Admin", "Approver":"Z:CWQ_IMO_P2W_Issuer", "Receiver":"Z:CWQ_IMO_P2W_Receiver"}
cf.api.destination=CW_IMO_ServiceUser_Creds
